---
steps:
  - name: 'docker'
    args: ['build', '-t', 'vwtdigital/cloudbuilder-dast', '.']

  - name: 'docker'
    args: ['tag', 'vwtdigital/cloudbuilder-dast:$TAG_NAME']

  # Get secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update -y
        apt-get install docker.io -y
        USERNAME=$(gcloud secrets versions access latest --secret="$PROJECT_ID"-username)
        PASSWORD=$(gcloud secrets versions access latest --secret="$PROJECT_ID"-password)
        docker login -u $$USERNAME -p $$PASSWORD
        if [[ "$BRANCH_NAME" == "master" ]]
        then
          docker tag vwtdigital/cloudbuilder-dast:latest
        fi
        docker push vwtdigital/cloudbuilder-dast
