schemaVersion: "2.0.0"

fileExistenceTests:
  - name: 'coverage entrypoint'
    path: '/workspace/dast.py'
    shouldExist: true
    isExecutableBy: 'owner'

metadataTest:
  entrypoint: ["python", "/workspace/dast.py"]
  workdir: "/workspace"

commandTests:
  - name: "python 3.7 exists"
    command: "python"
    args: ["--version"]
    expectedOutput: ['Python 3.7.\d+']
