schemaVersion: "2.0.0"

fileExistenceTests:
  - name: 'coverage entrypoint'
    path: '/usr/local/bin/docker-dast.sh'
    shouldExist: true
    isExecutableBy: 'owner'

metadataTest:
  entrypoint: ["docker-dast.sh"]
  workdir: "/workspace"

commandTests:
  - name: "python 3.7 exists"
    command: "which"
    args: ["/usr/bin/python3.7"]
    expectedOutput: ["/usr/bin/python3.7\n"]

# setup a virtualenv, and verify the correct python binary is run
  - name: "python 3.7 works in virtualenv"
    setup: [["virtualenv", "-p python3.7", "/venv"]]
    command: "python"
    args: ["--version"]
    expectedOutput: ["Python 3.7.\d+"]