schemaVersion: "2.0.0"

fileExistenceTests:
  - name: 'coverage entrypoint'
    path: '/usr/local/bin/dast.py'
    shouldExist: true
    isExecutableBy: 'owner'

metadataTest:
  entrypoint: ["python3", "/usr/local/bin/dast.py"]

commandTests:
  - name: "python 3.7 exists"
    command: "python3"
    args: ["--version"]
    expectedOutput: ['Python 3.7.\d+']
