schemaVersion: "2.0.0"

fileExistenceTests:
  - name: 'coverage entrypoint'
    path: '/usr/local/bin/docker-dast.sh'
    shouldExist: true
    isExecutableBy: 'owner'

metadataTest:
  entrypoint: ["docker-dast.sh"]
  workdir: "/workspace"

commandTests:
  - name: "python 3.7 exists"
    command: "python"
    args: ["--version"]
    expectedOutput: ['Python 3.7.\d+']
